[project]
name = "mips-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.6.0",
    "mip>=1.15.0",
    "optax>=0.2.4",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]
